version: '3.3'
services:
  lb:
    image: lb
    build: ./lb
    hostname: lb
    ports:
      - "80:80"
      - "83:81"
      - "82:82"
    volumes:
      - ./lb.conf:/etc/nginx/nginx.conf:ro
  nap:
    image: nap
    build: ./nap
    hostname: nap
    scale: 2
    volumes:
      - ./nap.conf:/etc/nginx/nginx.conf:ro
      - ./json:/etc/nginx/json:ro
  pool:
    image: nginxdemos/hello:plain-text
    scale: 2
