version: '3.3'
services:
  lb:
    image: lb
    build:
      context: .
      dockerfile: Dockerfile.lb
    ports:
      - "80:80"
      - "82:82"
    volumes:
      - ./lb.conf:/etc/nginx/nginx.conf:ro
  nap:
    image: nap
    build:
      context: .
      dockerfile: Dockerfile.nap
    deploy:
      replicas: 2
    volumes:
      - ./nap.conf:/etc/nginx/nginx.conf:ro
      - ./quota.js:/etc/nginx/quota.js:ro
      - ./policies:/etc/nginx/json:ro
  pool:
    image: nginxdemos/hello:plain-text
    deploy:
      replicas: 2

